-- =============================================================================
-- Dimension tables (Silver → Warehouse)
-- =============================================================================

USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE DIM_STORE (
    STORE_ID          VARCHAR(16)   NOT NULL,
    STORE_NAME        VARCHAR(200)  NOT NULL,
    STORE_TYPE        VARCHAR(32),
    REGION            VARCHAR(64),
    CITY              VARCHAR(100),
    STATE             VARCHAR(8),
    OPENED_DATE       DATE,
    SQUARE_FOOTAGE    NUMBER(10,0),
    IS_ACTIVE         BOOLEAN,
    DW_LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_STORE PRIMARY KEY (STORE_ID)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID        VARCHAR(16)   NOT NULL,
    PRODUCT_NAME      VARCHAR(200)  NOT NULL,
    CATEGORY          VARCHAR(64),
    SUBCATEGORY       VARCHAR(64),
    BRAND             VARCHAR(64),
    UNIT_COST         NUMBER(12,2),
    UNIT_PRICE        NUMBER(12,2),
    SKU               VARCHAR(64),
    IS_ACTIVE         BOOLEAN,
    DW_LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID       VARCHAR(16)   NOT NULL,
    FIRST_NAME        VARCHAR(100),
    LAST_NAME         VARCHAR(100),
    EMAIL             VARCHAR(255),
    LOYALTY_TIER      VARCHAR(32),
    SIGNUP_DATE       DATE,
    STATE             VARCHAR(8),
    IS_ACTIVE         BOOLEAN,
    DW_LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY          NUMBER(8,0)   NOT NULL,  -- YYYYMMDD
    FULL_DATE         DATE          NOT NULL,
    YEAR              NUMBER(4,0),
    QUARTER           NUMBER(1,0),
    MONTH             NUMBER(2,0),
    MONTH_NAME        VARCHAR(16),
    WEEK_OF_YEAR      NUMBER(2,0),
    DAY_OF_MONTH      NUMBER(2,0),
    DAY_NAME          VARCHAR(16),
    IS_WEEKEND        BOOLEAN,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);

-- Seed DIM_DATE for 2024 (calendar seed)
INSERT INTO DIM_DATE (
    DATE_KEY, FULL_DATE, YEAR, QUARTER, MONTH, MONTH_NAME,
    WEEK_OF_YEAR, DAY_OF_MONTH, DAY_NAME, IS_WEEKEND
)
SELECT
    TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) AS DATE_KEY,
    d AS FULL_DATE,
    YEAR(d),
    QUARTER(d),
    MONTH(d),
    MONTHNAME(d),
    WEEKOFYEAR(d),
    DAY(d),
    DAYNAME(d),
    CASE WHEN DAYOFWEEK(d) IN (0, 6) THEN TRUE ELSE FALSE END
FROM (
    SELECT DATEADD(DAY, SEQ4(), '2024-01-01'::DATE) AS d
    FROM TABLE(GENERATOR(ROWCOUNT => 366))
)
WHERE d <= '2024-12-31'::DATE;
