-- =============================================================================
-- Gold marts (views + tables) for BI tools
-- =============================================================================

USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA GOLD;

-- Daily sales by store
CREATE OR REPLACE TABLE MART_DAILY_SALES_BY_STORE AS
SELECT
    f.TRANSACTION_DATE,
    f.STORE_ID,
    s.STORE_NAME,
    s.REGION,
    s.STORE_TYPE,
    COUNT(DISTINCT f.TRANSACTION_ID) AS TRANSACTIONS,
    SUM(f.QUANTITY)                  AS UNITS_SOLD,
    SUM(f.GROSS_AMOUNT)              AS GROSS_REVENUE,
    SUM(f.NET_AMOUNT)                AS NET_REVENUE,
    SUM(f.DISCOUNT_AMOUNT)           AS DISCOUNT_TOTAL,
    SUM(f.COGS)                      AS COGS,
    SUM(f.GROSS_PROFIT)              AS GROSS_PROFIT,
    ROUND(SUM(f.NET_AMOUNT) / NULLIF(COUNT(DISTINCT f.TRANSACTION_ID), 0), 2) AS AVG_ORDER_VALUE,
    ROUND(SUM(f.GROSS_PROFIT) / NULLIF(SUM(f.NET_AMOUNT), 0) * 100, 2)       AS GROSS_MARGIN_PCT
FROM SILVER.FACT_SALES f
JOIN SILVER.DIM_STORE s ON f.STORE_ID = s.STORE_ID
GROUP BY 1, 2, 3, 4, 5;

-- Daily sales by category
CREATE OR REPLACE TABLE MART_DAILY_SALES_BY_CATEGORY AS
SELECT
    TRANSACTION_DATE,
    CATEGORY,
    COUNT(DISTINCT TRANSACTION_ID) AS TRANSACTIONS,
    SUM(QUANTITY)                  AS UNITS_SOLD,
    SUM(NET_AMOUNT)                AS NET_REVENUE,
    SUM(GROSS_PROFIT)              AS GROSS_PROFIT
FROM SILVER.FACT_SALES
GROUP BY 1, 2;

-- Customer lifetime value
CREATE OR REPLACE TABLE MART_CUSTOMER_LIFETIME_VALUE AS
SELECT
    f.CUSTOMER_ID,
    c.LOYALTY_TIER,
    c.STATE,
    MIN(f.TRANSACTION_DATE) AS FIRST_PURCHASE,
    MAX(f.TRANSACTION_DATE) AS LAST_PURCHASE,
    COUNT(DISTINCT f.TRANSACTION_ID) AS ORDER_COUNT,
    SUM(f.NET_AMOUNT)       AS LIFETIME_REVENUE,
    SUM(f.GROSS_PROFIT)     AS LIFETIME_PROFIT,
    ROUND(AVG(f.NET_AMOUNT), 2) AS AVG_ORDER_VALUE
FROM SILVER.FACT_SALES f
LEFT JOIN SILVER.DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE f.CUSTOMER_ID <> 'CUS00000'
GROUP BY 1, 2, 3;

-- Product performance
CREATE OR REPLACE TABLE MART_PRODUCT_PERFORMANCE AS
SELECT
    f.PRODUCT_ID,
    p.PRODUCT_NAME,
    f.CATEGORY,
    f.BRAND,
    p.UNIT_PRICE,
    SUM(f.QUANTITY)     AS UNITS_SOLD,
    SUM(f.NET_AMOUNT)   AS NET_REVENUE,
    SUM(f.GROSS_PROFIT) AS GROSS_PROFIT,
    COUNT(DISTINCT f.TRANSACTION_ID) AS ORDER_COUNT
FROM SILVER.FACT_SALES f
JOIN SILVER.DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY 1, 2, 3, 4, 5;

-- Channel / payment mix
CREATE OR REPLACE TABLE MART_CHANNEL_MIX AS
SELECT
    TRANSACTION_DATE,
    CHANNEL,
    PAYMENT_METHOD,
    COUNT(DISTINCT TRANSACTION_ID) AS TRANSACTIONS,
    SUM(NET_AMOUNT) AS NET_REVENUE
FROM SILVER.FACT_SALES
GROUP BY 1, 2, 3;

-- Secure view example for BI role
CREATE OR REPLACE VIEW V_STORE_REVENUE_YTD AS
SELECT
    REGION,
    STORE_NAME,
    SUM(NET_REVENUE) AS YTD_NET_REVENUE,
    SUM(GROSS_PROFIT) AS YTD_GROSS_PROFIT,
    SUM(TRANSACTIONS) AS YTD_TRANSACTIONS
FROM MART_DAILY_SALES_BY_STORE
GROUP BY 1, 2
ORDER BY YTD_NET_REVENUE DESC;
